development:
  adapter: postgresql
  database: triptri
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
production:
  adapter: postgresql
  host: localhost
  username: rails
  database: triptri
  password: OW2BCw04lI
  pool: 5
  timeout: 5000
  encoding: utf8