# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b13d695dcc665407734b5f77729fcc425fe7695c712b32debdaec1ad9af49f68fed8819cc70833327a879d1a71aa740064af5fab663eb78d48196fab18f6f405

test:
  secret_key_base: 3eb8698d4dffb2974f6d5b5bff1c9ab48dc28dca910b1c238855e3b0c35e24c5256e3589d77f23f3434733643954055c638b1c4ae9b874267e6fee6e181d6719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2eb8698d4dffb2974f6d5b5bff1c9ab48dc28dca910b1c238855e3b0c35e24c5256e3589d77f23f3434733643954055c638b1c4ae9b874267e6fee6e181d6719
