development:
  adapter: postgresql
  database: nutrisuporte_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: nutrisuporte_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nutrisuporte
  host: localhost
  username: nutrisuporte
  password: 5EVGo4eb
  pool: 5
  timeout: 5000
